### ISSUE TITLE
Doesn't work with Home Assistant 2023.5.1

### ISSUE THREAD

**Issue by Disane87** [jsmeyers/home-assistant-tuya-custom#1]
Since the new update this component isn't working anymore. Logs:
> 2023-05-05 09:16:05.476 ERROR (Thread-19 (_thread_main)) [tuya_iot] Unexpected disconnection.7
2023-05-05 09:16:05.712 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry [xyz@xyz.com] for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Do you need any other information?

**Comment by Aliskin-Papa** [comment]
Sam here

**Comment by carlito13500** [comment]
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1 
Interface utilisateur : 20230503.3 - latest 

Logger: homeassistant.config_entries
Source: custom_components/tuya/__init__.py:126
Integration: Tuya
First occurred: 19:21:22 (1 occurrences)
Last logged: 19:21:22

Error setting up entry xxxxxxxx@gmail.com for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by eduardocaraujo** [comment]
Same here. any news?

**Comment by capsel22** [comment]
getting the same error

**Comment by TBeisch** [comment]
getting also the same error

**Comment by TurboKanne** [comment]
Same for me, I already tried to remove it, but could not manage it. Everytime I remove it, it seems that there are some parts still there. Can someone please help with the info how to complete remove this? I treied to remove in HACS, but after upgrading to 5.4 the error log shows:

```
Logger: homeassistant.config_entries
Source: custom_components/tuya/__init__.py:126
Integration: Tuya
First occurred: 10:01:55 (1 occurrences)
Last logged: 10:01:55

Error setting up entry user_xxx@email_xxx.de for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

best regards

**Comment by TurboKanne** [comment]
@jsmeyers hi, could you please help me with this? some month ago you shared this custom integration or at least helped me with integrating it into my Home Assistant. It worked for my water valves, but with the new release of 2023.5.4 I have read that the custom integration stops the tuya integration. I tried to remove your custom, but it seems that there are some parts remaining.

could you please give a tip, how to completely remove the custom integration again?

thank you.
